language: java
jdk:
- oraclejdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: KjBwwtEOCqSI38neGM1dDPiRNLS8++RDV2V7n5/kPx570udiuROjm3zcytk2ssvdtXd9iPnsmgWD5xF+DduhV4+vpY3U59+u4NLcxuEFr21doqkFPwLrR/cixANZz5M+TknmqmN5h8buqy2Ww7T8MrgqJAGc15GOie2UhFDMPGrhwUJgP0fGLVBqGCkh83/ULTqZnXu/yWVM6VVrnEkxlgc5h99OdPOw/u4LrQYJpjArsYD4CRSkRvQT+nqkNJOxbdMxw1tBdNpRcxLbI6VwPQPPXMjfM73J2GsfBaBvsYQLZpr2oAP5GGYR8tCvRPqAqEg7h3EmbRalJuBWkWdz7OUyu1fuTE8R0IFVI9tpBCSBCzF8lKsz68EJEAbxc9kbYU13qFNaPUTn2vSRiWOzaCpoLgyDX7ERlhMQbssp51FeNZx9NOKvodoyXCb7C5k39ERc6G4LklecJ6utTz7FI/5XJLDq1IzZaffa1DeIpax1KpD/RLBNDcMND6hz99n5oU08suSjyD8l4sC3esJmOIVqT64Qyz9QHyo+gjkypgu5r6cul4uDM9wrf2RVH1qZYGEc5tPxoI7uhEnJMbd1LvGYkCxLwYbAQwOxwKTpzG1B3SeHJfbaeTGXKjiV2CWtljYv6ARgHqcgOCjU902qWcyr7c3WQFGWIovbFm88b9A=
